---
- name: check mandatory variables
  ansible.builtin.assert:
    that:
      - systemd_journald_configs is defined
      - systemd_journald_configs | length > 0
    quiet: true

- name: ensure data directory
  notify: systemd-tmpfiles create
  ansible.builtin.file:
    state: directory
    path: /var/log/journal

- name: ensure config directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/journald.conf.d

- name: ensure configs
  notify: restart systemd-journald service
  ansible.builtin.copy:
    dest: "/etc/systemd/journald.conf.d/{{ item.filename }}"
    content: "{{ item.content }}"
  loop: "{{ systemd_journald_configs }}"

- name: execute handlers
  ansible.builtin.meta: flush_handlers

- name: ensure systemd-journald started
  ansible.builtin.systemd:
    name: systemd-journald
    enabled: true
    state: started
